a = Analysis(
    ['..\\claudecli\\__main__.py'],
    pathex=['..', '..\\claudecli', 'C:\\Users\\Edward\\Programming\\claudecli\\venv\\Lib\\site-packages'],
    binaries=[],
    datas=[('..\\claudecli', 'claudecli')],
    hiddenimports=[
        "anthropic",
        "black",
        "certifi",
        "charset-normalizer",
        "click",
        "idna",
        "markdown-it-py",
        "mdurl",
        "mypy-extensions",
        "packaging",
        "pathspec",
        "platformdirs",
        "prompt-toolkit",
        "pygments",
        "pyyaml",
        "requests",
        "rich",
        "tomli",
        "typing_extensions",
        "urllib3",
        "wcwidth",
        "xdg-base-dirs",
        "pyperclip",
        "pysocks",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='claudecli',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    onefile=True,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='claudecli',
)
